### ISSUE TITLE
I get an HTTP error when trying to do a bolus in the CG app

### ISSUE THREAD

**Issue by sircsaba** [LoopKit/LoopCaregiver#47]
I installed the app without incidence this morning and was able to add my looper no problems. In the CG app I can see the BS and all the information. The looper version is 3.23 built almost 2 weeks ago and has no issues on a IPhone se 3rd gen. The CG app is on a SE 2nd gen. Looper is using a NS cgm and also a NS follower.
I see the OTP in loop and CG as the same.

When I bolus I get an error when trying to deliver after entering my pin.

I reinstalled the app a few times, rebooted the phone deleted and put on the looper all without success ! I have no more options to try. Any suggestions ?
![PXL_20240720_150911551](https://github.com/user-attachments/assets/f9a2c386-d624-4fde-a3df-5ee7d016b2b9)

**Comment by gestrich** [comment]
HI - I'd suggest getting support through Zulip rather than Github issues. The Github issues are meant more for feature requests and requests to fix known software bugs. I think at this point you just need the community to help you troubleshoot Nightscout.

The error message you posted suggests Nightscout is not communicating with the Loop properly and is possibly a Nightscout configuration issue. Again though I'd suggesting getting help in Zulip or Facebook.

**Comment by sircsaba** [comment]
I'm presently looking into my NS because there seems to be something not proper. Thanks.

**Comment by smlcngl** [comment]
Hello, 
Make sure that you have added parameters to nightscout web app
https://loopkit.github.io/loopdocs/nightscout/remote-config/#add-apn-variables-to-nightscout
regards,

**Comment by sircsaba** [comment]
FYI, the problem is solved and it seems to be Portainer that doesn't append the extra env variables and by putting them directly in the script everything seems to work. Also, you have to be careful to make sure that the key has the CR/LF because it won't be recognized. By using the \n it fixes this problem. It was just easier to go into the file manually and make the changes than going into portainer. Once this was done, everything worked like a charm. So beware when using Portainer and Making changes to the file !!
